import "./globals.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import localFont from "next/font/local";
import { SiteProvider } from "@/context/siteContext";

const satoshiRegular = localFont({
  src: "../fonts/Satoshi-Regular.woff2",
  weight: "400",
  variable: "--regular",
});

export const metadata = {
  title: "OTHON Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={satoshiRegular.variable}>
      <SiteProvider>
        {/* <body style={{ overflowX: "hidden" }}> */}
        <body>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </SiteProvider>
    </html>
  );
}
